Exercise 7 of chapter 11 completed.
Htocki/Stroustrup pull request #21
Opened 2020-04-18 19:21 UTC by Htocki

2020-04-18 20:30 UTC, sialiuk requested changes

2020-04-18 20:30 UTC, sialiuk commented on bin/11_7/src/Main.cpp
> +    std::vector<std::pair<std::string, std::string>> forms {
Should be const

2020-04-18 20:30 UTC, sialiuk commented on bin/11_7/src/Main.cpp
> +      while (buffer.find(contracted_form) != std::string::npos) {
You need to save the last position where a short form was found, then start finding from this position.

2020-04-21 14:31 UTC, Htocki commented on bin/11_7/src/Main.cpp
> +    std::vector<std::pair<std::string, std::string>> forms {
Fixed.

2020-04-29 12:36 UTC, sialiuk approved these changes

2020-04-29 12:37 UTC, merged