Exercise 10 of chapter 11 completed.
Htocki/Stroustrup pull request #23
Opened 2020-04-25 14:12 UTC by Htocki

2020-04-29 12:24 UTC, sialiuk requested changes

2020-04-29 12:24 UTC, sialiuk commented on bin/11_10/src/Main.cpp
> +void Print(const std::vector<std::string> vector) {
should be reference

2020-04-29 12:24 UTC, sialiuk commented on bin/11_10/src/Main.cpp
> +  const std::string string {
why not constexpr std::string_view

2020-05-14 16:29 UTC, Htocki commented on bin/11_10/src/Main.cpp
> +void Print(const std::vector<std::string> vector) {
Fixed.

2020-05-15 09:22 UTC, Htocki commented on bin/11_10/src/Main.cpp
> +  const std::string string {
Fixed.

2020-05-16 13:55 UTC, sialiuk approved these changes

2020-05-16 13:59 UTC, merged